### ISSUE TITLE
#include <immintrin.h> still needed?

### ISSUE THREAD

**Issue by Tiza59** [macroxue/bridge-solver#2]
I had to comment this line out to compile on Apple Clang. No side effects noted so far.

**Comment by macroxue** [comment]
It's needed for `_pext_u64` and `_pdep_u64` for BMI2 bit packing and extraction. The issue can be fixed by adding `#ifdef __BMI2__` around the include.

**Comment by macroxue** [comment]
Just pushed a commit d005d7e75635855e7b183bd066a4d0120bcb3d52, which should fix this issue.
